version: 0.2
phases:
  pre_build:
    commands:
      - echo Test started on `date`
      - echo Logging in to Amazon ECR....
      - mvn package
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 388362140757.dkr.ecr.us-east-1.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - APPLICATION_NAME=product-service
      - REPOSITORY_URI=388362140757.dkr.ecr.us-east-1.amazonaws.com/e-mandi
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $APPLICATION_NAME:$IMAGE_TAG .
      - docker tag $APPLICATION_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo pushing to repo
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"SpringBootAppContainer", "imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json